language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
    - "./gradlew clean check -i"

after_success:
    - "./gradlew jacocoRootReport coveralls"

after_failure:
    - "for i in *.png; do curl --upload-file $i https://transfer.sh/$i; done"

branches:
  only:
    - master
    - release

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer
